"""Curated skill -> learning resource map, hand-picked (never AI-generated) to avoid
hallucinated or broken URLs. Covers the top skills actually present in the ingested
job dataset. Shared between the analytics skills-gap heatmap and interview prep."""

LEARNING_LINKS = {
    "python": "https://docs.python.org/3/tutorial/",
    "sql": "https://www.w3schools.com/sql/",
    "javascript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    "git": "https://git-scm.com/doc",
    "github": "https://docs.github.com/en/get-started",
    "aws": "https://aws.amazon.com/getting-started/",
    "css": "https://developer.mozilla.org/en-US/docs/Web/CSS",
    "css3": "https://developer.mozilla.org/en-US/docs/Web/CSS",
    "html": "https://developer.mozilla.org/en-US/docs/Web/HTML",
    "html5": "https://developer.mozilla.org/en-US/docs/Web/HTML",
    "java": "https://docs.oracle.com/en/java/javase/17/docs/api/index.html",
    "node.js": "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
    "nodejs": "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
    "react": "https://react.dev/learn",
    "react.js": "https://react.dev/learn",
    "reactjs": "https://react.dev/learn",
    "mongodb": "https://www.mongodb.com/docs/manual/tutorial/getting-started/",
    "azure": "https://learn.microsoft.com/en-us/training/azure/",
    "angular": "https://angular.dev/tutorials",
    "docker": "https://docs.docker.com/get-started/",
    "mysql": "https://dev.mysql.com/doc/mysql-tutorial-excerpt/8.0/en/",
    "tableau": "https://www.tableau.com/learn/training",
    "typescript": "https://www.typescriptlang.org/docs/handbook/intro.html",
    "r": "https://www.r-project.org/other-docs.html",
    "power bi": "https://learn.microsoft.com/en-us/power-bi/fundamentals/",
    "kubernetes": "https://kubernetes.io/docs/tutorials/",
    "postgresql": "https://www.postgresql.org/docs/current/tutorial.html",
    "restful apis": "https://restfulapi.net/",
    "rest api": "https://restfulapi.net/",
    "excel": "https://support.microsoft.com/en-us/excel",
    "gcp": "https://cloud.google.com/docs/get-started",
    "spring boot": "https://spring.io/guides/gs/spring-boot/",
    "tensorflow": "https://www.tensorflow.org/tutorials",
    "redux": "https://redux.js.org/introduction/getting-started",
    "c#": "https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/",
    "pytorch": "https://pytorch.org/tutorials/",
    "php": "https://www.php.net/manual/en/tutorial.php",
    "jira": "https://www.atlassian.com/software/jira/guides",
    "express.js": "https://expressjs.com/en/starter/installing.html",
    "express": "https://expressjs.com/en/starter/installing.html",
    "jquery": "https://api.jquery.com/",
    "nosql": "https://www.mongodb.com/nosql-explained",
    "jenkins": "https://www.jenkins.io/doc/tutorials/",
    "microservices": "https://microservices.io/",
    "django": "https://docs.djangoproject.com/en/stable/intro/tutorial01/",
    "bootstrap": "https://getbootstrap.com/docs/5.3/getting-started/introduction/",
    "pandas": "https://pandas.pydata.org/docs/getting_started/index.html",
    "spark": "https://spark.apache.org/docs/latest/quick-start.html",
    "scikit-learn": "https://scikit-learn.org/stable/getting_started.html",
    "vue.js": "https://vuejs.org/guide/introduction.html",
    "graphql": "https://graphql.org/learn/",
    "kafka": "https://kafka.apache.org/documentation/#gettingStarted",
    "ci/cd": "https://about.gitlab.com/topics/ci-cd/",
    "sql server": "https://learn.microsoft.com/en-us/sql/sql-server/",
    "oracle": "https://docs.oracle.com/en/database/oracle/oracle-database/index.html",
    "c++": "https://cplusplus.com/doc/tutorial/",
    "numpy": "https://numpy.org/doc/stable/user/quickstart.html",
    "webpack": "https://webpack.js.org/guides/getting-started/",
    "jest": "https://jestjs.io/docs/getting-started",
    "machine learning": "https://developers.google.com/machine-learning/crash-course",
    "hadoop": "https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html",
    "redis": "https://redis.io/docs/latest/develop/get-started/",
    "deep learning": "https://www.deeplearning.ai/",
    "data analysis": "https://www.coursera.org/learn/python-data-analysis",
    "linux": "https://ubuntu.com/tutorials/command-line-for-beginners",
    "flask": "https://flask.palletsprojects.com/en/latest/quickstart/",
    "fastapi": "https://fastapi.tiangolo.com/tutorial/",
    "go": "https://go.dev/doc/tutorial/getting-started",
    "golang": "https://go.dev/doc/tutorial/getting-started",
    "rust": "https://doc.rust-lang.org/book/",
    "swift": "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/guidedtour/",
    "kotlin": "https://kotlinlang.org/docs/getting-started.html",
    "terraform": "https://developer.hashicorp.com/terraform/tutorials",
    "ansible": "https://docs.ansible.com/ansible/latest/getting_started/index.html",
    "elasticsearch": "https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html",
    "rabbitmq": "https://www.rabbitmq.com/tutorials",
    "nlp": "https://www.nltk.org/book/",
    "computer vision": "https://opencv.org/get-started/",
    "agile": "https://www.atlassian.com/agile",
    "scrum": "https://www.scrum.org/resources/what-is-scrum",
    "power apps": "https://learn.microsoft.com/en-us/power-apps/",
    "sap": "https://learning.sap.com/",
    "salesforce": "https://trailhead.salesforce.com/",
    "linux administration": "https://ubuntu.com/tutorials/command-line-for-beginners",
    "communication": "https://www.coursera.org/learn/wharton-communication-skills",
    "leadership": "https://www.coursera.org/learn/leadership-communication",
    "project management": "https://www.pmi.org/certifications/project-management-pmp/getting-started",
    "matplotlib": "https://matplotlib.org/stable/tutorials/index.html",
    "seaborn": "https://seaborn.pydata.org/tutorial.html",
    "matlab": "https://www.mathworks.com/help/matlab/getting-started-with-matlab.html",
    "airflow": "https://airflow.apache.org/docs/apache-airflow/stable/tutorial/index.html",
    "spacy": "https://spacy.io/usage/spacy-101",
    "opencv": "https://docs.opencv.org/4.x/d9/df8/tutorial_root.html",
    "looker": "https://cloud.google.com/looker/docs/intro-to-looker",
    "dbt": "https://docs.getdbt.com/docs/introduction",
    "snowflake": "https://docs.snowflake.com/en/user-guide-getting-started",
    "databricks": "https://docs.databricks.com/en/getting-started/index.html",
    "plotly": "https://plotly.com/python/getting-started/",
    "keras": "https://keras.io/getting_started/",
    "xgboost": "https://xgboost.readthedocs.io/en/stable/get_started.html",
    "azure devops": "https://learn.microsoft.com/en-us/azure/devops/get-started/",
    "unit testing": "https://docs.python.org/3/library/unittest.html",
    "selenium": "https://www.selenium.dev/documentation/webdriver/getting_started/",
    "postman": "https://learning.postman.com/docs/getting-started/overview/",
    "linear regression": "https://scikit-learn.org/stable/modules/linear_model.html",
    "statistics": "https://www.khanacademy.org/math/statistics-probability",
    "big data": "https://hadoop.apache.org/docs/stable/",
    "data visualization": "https://www.tableau.com/learn/training",
    "data engineering": "https://www.coursera.org/professional-certificates/gcp-data-engineering",
    "data wrangling": "https://pandas.pydata.org/docs/getting_started/index.html",
    "data science": "https://www.coursera.org/professional-certificates/ibm-data-science",
    "data modeling": "https://www.postgresql.org/docs/current/tutorial.html",
    "etl": "https://airflow.apache.org/docs/apache-airflow/stable/tutorial/index.html",
    "api development": "https://fastapi.tiangolo.com/tutorial/",
    "api testing": "https://learning.postman.com/docs/getting-started/overview/",
    "vue": "https://vuejs.org/guide/introduction.html",
    "next.js": "https://nextjs.org/learn",
    "nextjs": "https://nextjs.org/learn",
    "nest.js": "https://docs.nestjs.com/first-steps",
    "nestjs": "https://docs.nestjs.com/first-steps",
    ".net": "https://learn.microsoft.com/en-us/dotnet/core/introduction",
    "asp.net": "https://learn.microsoft.com/en-us/aspnet/core/getting-started/",
    "dotnet": "https://learn.microsoft.com/en-us/dotnet/core/introduction",
    "objective-c": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html",
    "android": "https://developer.android.com/courses",
    "ios": "https://developer.apple.com/tutorials/swiftui",
    "flutter": "https://docs.flutter.dev/get-started/install",
    "react native": "https://reactnative.dev/docs/getting-started",
    "shell scripting": "https://www.gnu.org/software/bash/manual/bash.html",
    "bash": "https://www.gnu.org/software/bash/manual/bash.html",
    "powershell": "https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/00-introduction",
    "cybersecurity": "https://www.cisa.gov/cybersecurity-training-exercises",
    "penetration testing": "https://owasp.org/www-project-web-security-testing-guide/",
    "network security": "https://www.cisco.com/c/en/us/training-events/training-certifications.html",
    "blockchain": "https://ethereum.org/en/developers/docs/",
    "solidity": "https://docs.soliditylang.org/en/latest/",
    "seo": "https://developers.google.com/search/docs/fundamentals/seo-starter-guide",
    "digital marketing": "https://learndigital.withgoogle.com/digitalgarage",
    "content writing": "https://www.coursera.org/learn/good-with-words-writing-and-editing",
    "figma": "https://help.figma.com/hc/en-us/categories/360002051613-Getting-started",
    "ui/ux": "https://www.interaction-design.org/courses",
    "ui design": "https://www.interaction-design.org/courses",
    "ux design": "https://www.interaction-design.org/courses",
    "adobe photoshop": "https://helpx.adobe.com/photoshop/tutorials.html",
    "adobe illustrator": "https://helpx.adobe.com/illustrator/tutorials.html",
    "sass": "https://sass-lang.com/guide/",
    "tailwind css": "https://tailwindcss.com/docs/installation",
    "tailwindcss": "https://tailwindcss.com/docs/installation",
    "webrtc": "https://webrtc.org/getting-started/overview",
    "websockets": "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API",
    "grpc": "https://grpc.io/docs/languages/python/quickstart/",
    "unity": "https://learn.unity.com/",
    "unreal engine": "https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-5-hub",
    "sales": "https://trailhead.salesforce.com/",
    "customer service": "https://www.coursera.org/learn/customer-service-fundamentals",
    "human resources": "https://www.shrm.org/topics-tools",
    "accounting": "https://www.coursera.org/professional-certificates/intuit-bookkeeping",
    "financial modeling": "https://corporatefinanceinstitute.com/resources/financial-modeling/",
    # Common tag-variant aliases and additional real-world skills found by cross-checking
    # against the actual ingested dataset's top 150 most-frequent skill tags.
    "google cloud": "https://cloud.google.com/docs/get-started",
    "react js": "https://react.dev/learn",
    "ci/cd pipelines": "https://about.gitlab.com/topics/ci-cd/",
    "rest apis": "https://restfulapi.net/",
    "json": "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON",
    ".net core": "https://learn.microsoft.com/en-us/dotnet/core/introduction",
    "wordpress": "https://wordpress.org/documentation/",
    "rest": "https://restfulapi.net/",
    "spring": "https://spring.io/guides/gs/spring-boot/",
    "xml": "https://developer.mozilla.org/en-US/docs/Web/XML/XML_introduction",
    "hibernate": "https://hibernate.org/orm/documentation/",
    "devops": "https://aws.amazon.com/devops/what-is-devops/",
    "sas": "https://www.sas.com/en_us/training.html",
    "pyspark": "https://spark.apache.org/docs/latest/api/python/getting_started/index.html",
    "confluence": "https://www.atlassian.com/software/confluence/guides",
    "powerbi": "https://learn.microsoft.com/en-us/power-bi/fundamentals/",
    "restful api": "https://restfulapi.net/",
    "scala": "https://docs.scala-lang.org/getting-started/index.html",
    "ms excel": "https://support.microsoft.com/en-us/excel",
    "s3": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/GetStartedWithS3.html",
    "laravel": "https://laravel.com/docs/getting-started",
    "angularjs": "https://angular.dev/tutorials",
    "ajax": "https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX",
    "junit": "https://junit.org/junit5/docs/current/user-guide/",
    "postgres": "https://www.postgresql.org/docs/current/tutorial.html",
    "babel": "https://babeljs.io/docs/",
    "maven": "https://maven.apache.org/guides/getting-started/",
    "apis": "https://restfulapi.net/",
    "npm": "https://docs.npmjs.com/getting-started",
    "hive": "https://cwiki.apache.org/confluence/display/hive/gettingstarted",
    "powerpoint": "https://support.microsoft.com/en-us/powerpoint",
    "node js": "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
    "agile methodologies": "https://www.atlassian.com/agile",
    "nosql databases": "https://www.mongodb.com/nosql-explained",
    "lambda": "https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html",
    "vba": "https://learn.microsoft.com/en-us/office/vba/library-reference/concepts/getting-started-with-vba-in-office",
    "microservices architecture": "https://microservices.io/",
    "mvc": "https://developer.mozilla.org/en-US/docs/Glossary/MVC",
    "microsoft excel": "https://support.microsoft.com/en-us/excel",
    "ai": "https://developers.google.com/machine-learning/crash-course",
    "mocha": "https://mochajs.org/#getting-started",
    "google analytics": "https://support.google.com/analytics/answer/9304153",
    "jwt": "https://jwt.io/introduction",
    "core java": "https://docs.oracle.com/en/java/javase/17/docs/api/index.html",
    "springboot": "https://spring.io/guides/gs/spring-boot/",
    "cassandra": "https://cassandra.apache.org/doc/latest/cassandra/getting_started/index.html",
    "gitlab": "https://docs.gitlab.com/ee/tutorials/",
    "dynamodb": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStartedDynamoDB.html",
    "soap": "https://www.w3.org/TR/soap/",
    "ruby": "https://www.ruby-lang.org/en/documentation/quickstart/",
    "redshift": "https://docs.aws.amazon.com/redshift/latest/gsg/getting-started.html",
    "mern stack": "https://www.mongodb.com/resources/languages/mern-stack",
    "j2ee": "https://docs.oracle.com/javaee/7/tutorial/",
    "alteryx": "https://community.alteryx.com/t5/Learn-Alteryx/ct-p/tacademy",
    "entity framework": "https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app",
    "oauth": "https://oauth.net/2/",
    "langchain": "https://python.langchain.com/docs/introduction/",
    "spring framework": "https://spring.io/guides/gs/spring-boot/",
}


def get_learning_link(skill: str) -> str:
    return LEARNING_LINKS.get(skill.strip().lower())
